### PR TITLE
fix: switch out SGID-based UTA data for UTA's portal

### PR DESCRIPTION
**Pull request by stdavis**
Ref: agrc/porter#331, agrc/porter#332, agrc/porter#334,
agrc/porter#333

@ZachBeck: I just pushed an update to https://locate.dev.utah.gov/ that switches out the UTA data from SGID with their portal data. Would you mind taking a look and making sure that I didn't break anything? I've got to run but the deploy should be done in the next 10 minutes. Thanks!

- [ ] publish a new map service and check the layer ids before these changes are deployed

### CODE REVIEW

**Review by steveoh — APPROVED** [review]
technical review looks good. 

Is it normal that light rail is bundled into commuter rail?

**Comment by stdavis** [comment]
> Is it normal that light rail is bundled into commuter rail?

Yes, it's been that way since the beginning, IIRC.

**Comment by ZachBeck** [comment]
I don't remember what the old version was like. Should the stops have more info than just the color of the trax line?

**Comment by stdavis** [comment]
Here's a link to the current app: https://locate.utah.gov/

But it sounds like you may not be any more familiar with the UTA data in this app that I am. I fixed the popups for the stations so that they show the station name rather than the route name. I'm going to call this good. Thanks for catching that.

**Pull request merged**
